[package]
name = "hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_search = "2.1.0"
convert_case = "0.6.0"
git2 = "0.18.1"
